[project]
name = "nexnode"
version = "0.1.0"
description = "A node-based agentic framework designed for maximum control and minimal abstraction."
readme = "README.md"
authors = [
    { name = "S-Astralcoder", email = "suraj.astralcode.ai@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]

[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyrefly>=1.3.2",
    "ruff>=0.16.10",
]
